clean: true
objc: true
theme: fullwidth
output: docs.zh-cn
sdk: iphonesimulator
readme: README.zh-cn.md
umbrella_header: .jazzy.zh-cn/MovieousShortVideo/MovieousShortVideo.h
framework_root: .jazzy.zh-cn