use_frameworks!
platform :ios, '9.0'
target 'MovieousShortVideoDemo' do
  pod 'MovieousShortVideo', :path => '../'
  pod 'Masonry'
  pod 'TZImagePickerController'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'M13ProgressSuite'
  pod 'FDWaveformView'
  pod 'SSZipArchive'
end
