//
//  MSVClip.h
//  MovieousShortVideo
//
//  Created by Chris Wang on 2019/4/13.
//  Copyright © 2019 Movieous Team. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "MSVTypeDefines.h"
#import <MovieousBase/MovieousBase.h>

NS_ASSUME_NONNULL_BEGIN

@interface MSVClip : NSObject
<
NSCopying
>

/**
 * @brief Initialize a clip
 * @param type Type of clip
 * @param URL The file path of the clip supports local files only
 * @param outError If an error occurs, return the error that occurred
 * @return If the initialization is successful, the completed object is returned, otherwise returns nil
 */
- (instancetype)initWithType:(MSVClipType)type URL:(NSURL *)URL error:(NSError **)outError;

/**
 * @brief Initialize a clip of an audio and video type using AVAsset
 * @param asset AVAsset object used to create the clip
 * @param outError If an error occurs, return the error that occurred
 * @return If the initialization is successful, the completed object is returned, otherwise returns nil
 */
- (instancetype)initWithAsset:(AVAsset *)asset error:(NSError **)outError;

/**
 * @brief Initialize a clip of a image type using UIImage
 * @param image UIImage object used to create the clip
 * @param duration Image duration
 * @param outError If an error occurs, return the error that occurred
 * @return If the initialization is successful, the completed object is returned, otherwise returns nil
 */
- (instancetype)initWithImage:(UIImage *)image duration:(NSTimeInterval)duration error:(NSError **)outError;

/**
 * @brief Initialize a clip with a existing clip
 * @param clip The existing clip
 * @return If the initialized instance
 */
- (instancetype)initWithClip:(MSVClip *)clip;

/**
 * @brief User-defined ID field, you can use this property to store information you want to associate to this object
 */
@property (nonatomic, strong) NSString *ID;

/**
 * @brief Type of the clip object
 */
@property (nonatomic, assign, readonly) MSVClipType type;

/**
 * @brief Media file URL
 */
@property (nonatomic, strong, readonly) NSURL *URL;

/**
 * @brief The frame in the source video spece which will be used to display in destination video
 */
@property (nonatomic, assign) CGRect sourceDisplayFrame;

/**
 * @brief The frame in destination video space you want to place the source display video.
 */
@property (nonatomic, assign) CGRect destDisplayFrame;

/**
 * @brief The angle you want to rotate the display area, rotation will be applied after the source video has been placed correctly in the destDisplayFrame, and the anchor point is at the center of the destDisplayFrame in the destination video space.
 */
@property (nonatomic, assign) float rotateAngle;

/**
 * @brief The scaling mode you want to use if the aspect ratio of sourceDisplayFrame and destDisplayFrame are not equal.
 */
@property (nonatomic, assign) MovieousScalingMode scalingMode;

/**
 * @brief The duration of the clip in the main track, the durationAtMainTrack parameter and speed affect each other, the specific operational relationship is： speed = timeRange.duration / durationAtMainTrack
 */
@property (nonatomic, assign) NSTimeInterval durationAtMainTrack;


// The following parameters are only valid for the clip of the MSVClipTypeAV type
#pragma mark - video properties
/**
 * @brief The AVAsset object generated by the audio and video media files, you can get some required parameters here.
 */
@property (nonatomic, strong, readonly) AVAsset *asset;

/**
 * @brief Intercepting the time range that used in the media clip.
 * @warning This time range refers to the time range without the fast and slow processing and reverses processing,Also, if timeRange.startTime + timeRange.duration > total media duration,  the excess part will be ignored.
 */
@property (nonatomic, assign) MovieousTimeRange timeRange;

/**
 * @brief Speed of the audio clip
 * Generally, the following configuration can be performed：
 * Extremely fast：2.0
 * Fast：1.5
 * Standard：1.0
 * Slow：0.75
 * Extremely slow：0.5
 */
@property (nonatomic, assign) float speed;

/**
 * @brief The volume of the media audio, defaults to the preferredVolume that comes with the media file.
 */
@property (nonatomic, assign) float volume;

// The following parameters are only valid for the clip of the MSVClipTypeImage type
#pragma mark - image properties
/**
 * @brief Image object
 */
@property (nonatomic, assign, readonly) UIImage *image;

/**
 * @brief Refresh inner Asset objects，need to be called when received `AVAudioSessionMediaServicesWereResetNotification` notification
 */
- (void)refreshAsset;

@end

NS_ASSUME_NONNULL_END
